### ISSUE TITLE
Remove /*! special comments from minified JS

### ISSUE THREAD

**Issue by apeschar** [kiboit/phast#1]
A customer notes that comments in scripts like `/*! ... */` weren't removed by Phast, and that PageSpeed Insights complained. (Such comments are used for copyright notices and thus not removed by some minifiers.)

I'm not sure that this script was actually loaded through Phast, so we should test whether this is actually the case.

If it turns out that we do indeed not remove these comments, we should change that.

**Comment by mkosturkov** [comment]
The minifier that we use does not remove those comments. We will add the option to do that, but leave it switched off by default, since those comments often contain licenses.
