### ISSUE TITLE
Document the configuration options

### ISSUE THREAD

**Issue by adrenth** [kiboit/phast#12]
Hi @apeschar,

Is it possible to document the configuration options which are available in this package? So we can keep track changes in configuration?

We ship this default configuration package with the October CMS plugin: 
https://github.com/vdlp/oc-phast-plugin/blob/develop/config.php

I'm not sure if these are all the configuration options available. Just a check up.

Keep doing this awesome work ;-)

**Comment by apeschar** [comment]
Hey @adrenth,

All possible configuration options are listed in [DefaultConfiguration.php](https://github.com/kiboit/phast/blob/master/src/Environment/DefaultConfiguration.php).

Generally, there is no need to change anything, it should be plug and play.

More documentation would of course be a good thing, but it's not really high on my list of priorities.

--Albert
