### ISSUE TITLE
Getting Not Found errors on a localhost

### ISSUE THREAD

**Issue by 01Kuzma** [kiboit/phast#14]
Hi!
Trying to test the plug-in on localhost with a October CMS. This CMS have a plug-in wrapper for `phast`.
All settings are default.
I've set the `.htaccess` as it's documented:

```
<IfModule mod_rewrite.c>

    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On

    ##
    ## You may need to uncomment the following line for some hosting environments,
    ## if you have installed to a subdirectory, enter the name here also.
    ##
    # RewriteBase /
    
    ##
    ## Uncomment following lines to force HTTPS.
    ##
    # RewriteCond %{HTTPS} off
    # RewriteRule (.*) https://%{SERVER_NAME}/$1 [L,R=301]

    ##
    ## Black listed folders
    ##
    RewriteRule ^bootstrap/.* index.php [L,NC]
    RewriteRule ^config/.* index.php [L,NC]
    RewriteRule ^vendor/.* index.php [L,NC]
    RewriteRule ^storage/cms/.* index.php [L,NC]
    RewriteRule ^storage/logs/.* index.php [L,NC]
    RewriteRule ^storage/framework/.* index.php [L,NC]
    RewriteRule ^storage/temp/protected/.* index.php [L,NC]
    RewriteRule ^storage/app/uploads/protected/.* index.php [L,NC]

    ##
    ## White listed folders
    ##
    RewriteCond %{REQUEST_FILENAME} -f
    RewriteCond %{REQUEST_URI} !^/plugins/vdlp/phast/phast\.php*	
    RewriteCond %{REQUEST_FILENAME} !/.well-known/*
    RewriteCond %{REQUEST_FILENAME} !/storage/app/uploads/.*
    RewriteCond %{REQUEST_FILENAME} !/storage/app/media/.*
    RewriteCond %{REQUEST_FILENAME} !/storage/temp/public/.*
    RewriteCond %{REQUEST_FILENAME} !/themes/.*/(assets|resources)/.*
    RewriteCond %{REQUEST_FILENAME} !/plugins/.*/(assets|resources)/.*
    RewriteCond %{REQUEST_FILENAME} !/modules/.*/(assets|resources)/.*
    RewriteRule !^index.php index.php [L,NC]	

    ##
    ## Block all PHP files, except index
    ##
    RewriteCond %{REQUEST_FILENAME} -f
    RewriteCond %{REQUEST_URI} !^/plugins/vdlp/phast/phast\.php*
    RewriteCond %{REQUEST_FILENAME} \.php$
    RewriteRule !^index.php index.php [L,NC]

    ##
    ## Standard routes
    ##
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]	
	
</IfModule>

```

But getting `Not Found` errors:
`

GET | http://localhost/plugins/vdlp/phast/phast.php/__p__.js/https-3A-2F-2Ffonts.googleapis.com-2Fcss-3Ffamily-3DPoppins-3A300-2C300i-2C400-2C400i-2C500-2C500i-2C600-2C600i-2C700-2C700i-26display-3Dswap/service=css/cacheMarker=3c8b02e196559f4dcc8e077a72150367-2D223565/token=68a6d8a9f861cbc3/__p__.js
-- | --`

Any suggestions? Am I missing something?
Thank you!

**Comment by apeschar** [comment]
It might have to do with PATH_INFO not being supported on your server.  Meaning, `phast.php` is not accessible if it is followed by an additional path.

What do you see if you visit this URL instead?

http://localhost/plugins/vdlp/phast/phast.php

**Comment by 01Kuzma** [comment]
Thank you for answer!
I'm getting:
```
Object not found!

The requested URL was not found on this server. If you entered the URL manually please check your spelling and try again.

If you think this is a server error, please contact the webmaster.
Error 404
```

I'm running XAMPP on Winodws, so it could be the issue?

**Comment by apeschar** [comment]
Could you try adding this as your first rewrite rule, right after `RewriteEngine on`?

~~~
RewriteRule ^plugins/vdlp/phast/phast\.php - [L]
~~~

Do you still get the same error after doing that?  If so, could you ensure that the plugins/vdlp/phast/phast.php file actually exists?

**Comment by 01Kuzma** [comment]
well, it's the same :(
I'm attaching the screenshot to demonstrate:
![image](https://user-images.githubusercontent.com/569504/103541975-e778f880-4ea4-11eb-852e-561205d1a5e6.png)

**Comment by apeschar** [comment]
Your site is in `/fs`, but the URL that is requested is not.  It should be:

http://localhost/fs/plugins/vdlp/phast/phast.php

I'm not sure if the October CMS plugin supports this (I didn't build it).  But try moving your site to your server root directory (or creating a new virtual host with only this site in the root directory).

**Comment by 01Kuzma** [comment]
Thank you!
I will try
