### ISSUE TITLE
october:mirror command

### ISSUE THREAD

**Issue by dreamci** [kiboit/phast#15]
Hello,

Is there any workaround to make this work for sites with /public document root?

Thanks

**Comment by apeschar** [comment]
I'm not sure.  I did not author the October CMS integration, so cannot provide support for it.

There should be a settings file in the integration that contains the URL to `phast.php`.  This should be changed to include the `public` prefix or whatever you're using.

**Comment by dreamci** [comment]
Thanks, I will check it.
For some reason, https://octobercms.com/plugin/vdlp-phast this plugin support button opens this page instead of https://github.com/vdlp/oc-phast-plugin.
