### ISSUE TITLE
Phast console warnings

### ISSUE THREAD

**Issue by Artful-dodger** [kiboit/phast#17]
I have installed the plugin but are getting the following comments any thoughts on how to rectify 
Resource interpreted as Stylesheet but transferred with MIME type text/html: "<URL>".
:formatted:2472 [Phast] Client-side performance metrics
:formatted:2579 [Phast] Failed to load CSS {ref: "dYqrF8HzXyw"} undefined
(anonymous) @ :formatted:2579
tryCatch @ :formatted:1633
invokeCallback @ :formatted:1646
publish @ :formatted:1624
publishRejection @ :formatted:1580
flush @ :formatted:1430
characterData (async)
(anonymous) @ :formatted:1406
asap @ :formatted:1368
reject @ :formatted:1598
rejectPromise @ :formatted:1677
(anonymous) @ :formatted:2132
handleError @ :formatted:2131
(anonymous) @ :formatted:2107
successHandler @ :formatted:1994
load (async)
makeRequest @ :formatted:2003
flush @ :formatted:1982
setTimeout (async)
(anonymous) @ :formatted:1967
initializePromise @ :formatted:1674
Promise @ :formatted:1816
get @ :formatted:1959
(anonymous) @ :formatted:1931
tryCatch @ :formatted:1633
invokeCallback @ :formatted:1646
publish @ :formatted:1624
publishRejection @ :formatted:1580
flush @ :formatted:1430
characterData (async)
(anonymous) @ :formatted:1406
asap @ :formatted:1368
fulfill @ :formatted:1589
resolve @ :formatted:1573
resolvePromise @ :formatted:1675
request.onsuccess @ :formatted:2229
IndexedDB (async)
(anonymous) @ :formatted:2152
tryCatch @ :formatted:1633
invokeCallback @ :formatted:1646
publish @ :formatted:1624
flush @ :formatted:1430
characterData (async)
(anonymous) @ :formatted:1406
asap @ :formatted:1368
fulfill @ :formatted:1589
handleMaybeThenable @ :formatted:1559
resolve @ :formatted:1571
resolvePromise @ :formatted:1675
request.onsuccess @ :formatted:2229
IndexedDB (async)
openDB @ :formatted:2275
get @ :formatted:2259
openStore @ :formatted:2175
get @ :formatted:2151
get @ :formatted:2317
get @ :formatted:2305
get @ :formatted:1925
(anonymous) @ :formatted:2575
phast.scripts.phast.forEachSelectedElement @ :formatted:2397
(anonymous) @ :formatted:2571
(anonymous) @ :formatted:1325
phastScripts @ :formatted:3042
(anonymous) @ :formatted:3044
:formatted:2585 [Phast] Falling back to <link> element for http://test.com/themes/drift-in-laundry/assets/css/stroke7/stroke7-icon-font.min.css
:formatted:2579 [Phast] Failed to load CSS {ref: "zzEWrFMp_Rw"} undefined
(anonymous) @ :formatted:2579
tryCatch @ :formatted:1633
invokeCallback @ :formatted:1646
publish @ :formatted:1624
publishRejection @ :formatted:1580
flush @ :formatted:1430
characterData (async)
(anonymous) @ :formatted:1406
asap @ :formatted:1368
reject @ :formatted:1598
rejectPromise @ :formatted:1677
(anonymous) @ :formatted:2132
handleError @ :formatted:2131
(anonymous) @ :formatted:2107
successHandler @ :formatted:1994
load (async)
makeRequest @ :formatted:2003
flush @ :formatted:1982
setTimeout (async)
(anonymous) @ :formatted:1967
initializePromise @ :formatted:1674
Promise @ :formatted:1816
get @ :formatted:1959
(anonymous) @ :formatted:1931
tryCatch @ :formatted:1633
invokeCallback @ :formatted:1646
publish @ :formatted:1624
publishRejection @ :formatted:1580
flush @ :formatted:1430
characterData (async)
(anonymous) @ :formatted:1406
asap @ :formatted:1368
fulfill @ :formatted:1589
resolve @ :formatted:1573
resolvePromise @ :formatted:1675
request.onsuccess @ :formatted:2229
IndexedDB (async)
(anonymous) @ :formatted:2152
tryCatch @ :formatted:1633
invokeCallback @ :formatted:1646
publish @ :formatted:1624
flush @ :formatted:1430
characterData (async)
(anonymous) @ :formatted:1406
asap @ :formatted:1368
fulfill @ :formatted:1589
handleMaybeThenable @ :formatted:1559
resolve @ :formatted:1571
resolvePromise @ :formatted:1675
request.onsuccess @ :formatted:2229
IndexedDB (async)
openDB @ :formatted:2275
get @ :formatted:2259
openStore @ :formatted:2175
get @ :formatted:2151
get @ :formatted:2317
get @ :formatted:2305
get @ :formatted:1925
(anonymous) @ :formatted:2575
phast.scripts.phast.forEachSelectedElement @ :formatted:2397
(anonymous) @ :formatted:2571
(anonymous) @ :formatted:1325
phastScripts @ :formatted:3042
(anonymous) @ :formatted:3044
:formatted:2585 [Phast] Falling back to <link> element for http://test.com/modules/system/assets/css/framework.extras-min.css"
it appears to be something to do with stroke7-icon-font.min.css and framework.extras-min.css

**Comment by apeschar** [comment]
This probably has something to do with the AJAX request that is used to retrieve your stylesheets.

Could you share the URL of your site with me so I can have a look at the requests and responses that are being sent? If you don't want to post it here, you can email me at albert@peschar.net.

**Comment by Artful-dodger** [comment]
Hi Albert,
I have as yet use this on a live website only on my local test server as I am trying to improve the loading speed of my website, I have tried it on my live site with these resulting errors [Phast] Client-side performance metrics
(index):977 GET https://drift-in.co.uk/plugins/vdlp/phast/phast.php/__p__.js?service=bundler&r=XGbAlamj-G0 500
makeRequest @ (index):977
flush @ (index):976
setTimeout (async)
(anonymous) @ (index):975
initializePromise @ (index):952
Promise @ (index):964
get @ (index):974
(anonymous) @ (index):973
tryCatch @ (index):948
invokeCallback @ (index):949
publish @ (index):946
publishRejection @ (index):939
flush @ (index):918
characterData (async)
(anonymous) @ (index):915
asap @ (index):910
fulfill @ (index):941
resolve @ (index):937
resolvePromise @ (index):952
request.onsuccess @ (index):998
IndexedDB (async)
(anonymous) @ (index):994
tryCatch @ (index):948
invokeCallback @ (index):949
publish @ (index):946
flush @ (index):918
characterData (async)
(anonymous) @ (index):915
asap @ (index):910
fulfill @ (index):941
handleMaybeThenable @ (index):936
resolve @ (index):937
resolvePromise @ (index):952
request.onsuccess @ (index):998
IndexedDB (async)
openDB @ (index):1002
get @ (index):998
openStore @ (index):994
get @ (index):994
get @ (index):1004
get @ (index):1003
get @ (index):972
(anonymous) @ (index):1025
phast.scripts.phast.forEachSelectedElement @ (index):1011
(anonymous) @ (index):1025
(anonymous) @ (index):900
phastScripts @ (index):1054
(anonymous) @ (index):1054
(index):1025 [Phast] Failed to load CSS {ref: "XGbAlamj-G0"} undefined
(anonymous) @ (index):1025
tryCatch @ (index):948
invokeCallback @ (index):949
publish @ (index):946
publishRejection @ (index):939
flush @ (index):918
characterData (async)
(anonymous) @ (index):915
asap @ (index):910
reject @ (index):943
rejectPromise @ (index):952
(anonymous) @ (index):994
handleError @ (index):994
successHandler @ (index):977
load (async)
makeRequest @ (index):977
flush @ (index):976
setTimeout (async)
(anonymous) @ (index):975
initializePromise @ (index):952
Promise @ (index):964
get @ (index):974
(anonymous) @ (index):973
tryCatch @ (index):948
invokeCallback @ (index):949
publish @ (index):946
publishRejection @ (index):939
flush @ (index):918
characterData (async)
(anonymous) @ (index):915
asap @ (index):910
fulfill @ (index):941
resolve @ (index):937
resolvePromise @ (index):952
request.onsuccess @ (index):998
IndexedDB (async)
(anonymous) @ (index):994
tryCatch @ (index):948
invokeCallback @ (index):949
publish @ (index):946
flush @ (index):918
characterData (async)
(anonymous) @ (index):915
asap @ (index):910
fulfill @ (index):941
handleMaybeThenable @ (index):936
resolve @ (index):937
resolvePromise @ (index):952
request.onsuccess @ (index):998
IndexedDB (async)
openDB @ (index):1002
get @ (index):998
openStore @ (index):994
get @ (index):994
get @ (index):1004
get @ (index):1003
get @ (index):972
(anonymous) @ (index):1025
phast.scripts.phast.forEachSelectedElement @ (index):1011
(anonymous) @ (index):1025
(anonymous) @ (index):900
phastScripts @ (index):1054
(anonymous) @ (index):1054
(index):1026 [Phast] Falling back to <link> element for https://drift-in.co.uk/modules/system/assets/css/framework.extras-min.css
(index):977 GET https://drift-in.co.uk/plugins/vdlp/phast/phast.php/__p__.js?service=bundler&r=Kdb_TpKnsdU&r=PYmVLVVd-Eg 500
makeRequest @ (index):977
flush @ (index):976
setTimeout (async)
(anonymous) @ (index):975
initializePromise @ (index):952
Promise @ (index):964
get @ (index):974
(anonymous) @ (index):973
tryCatch @ (index):948
invokeCallback @ (index):949
publish @ (index):946
publishRejection @ (index):939
flush @ (index):918
characterData (async)
(anonymous) @ (index):915
asap @ (index):910
fulfill @ (index):941
resolve @ (index):937
resolvePromise @ (index):952
request.onsuccess @ (index):998
IndexedDB (async)
(anonymous) @ (index):994
tryCatch @ (index):948
invokeCallback @ (index):949
publish @ (index):946
flush @ (index):918
characterData (async)
(anonymous) @ (index):915
asap @ (index):910
reject @ (index):943
rejectPromise @ (index):952
(anonymous) @ (index):994
handleError @ (index):994
successHandler @ (index):977
load (async)
makeRequest @ (index):977
flush @ (index):976
setTimeout (async)
(anonymous) @ (index):975
initializePromise @ (index):952
Promise @ (index):964
get @ (index):974
(anonymous) @ (index):973
tryCatch @ (index):948
invokeCallback @ (index):949
publish @ (index):946
publishRejection @ (index):939
flush @ (index):918
characterData (async)
(anonymous) @ (index):915
asap @ (index):910
fulfill @ (index):941
resolve @ (index):937
resolvePromise @ (index):952
request.onsuccess @ (index):998
IndexedDB (async)
(anonymous) @ (index):994
tryCatch @ (index):948
invokeCallback @ (index):949
publish @ (index):946
flush @ (index):918
characterData (async)
(anonymous) @ (index):915
asap @ (index):910
fulfill @ (index):941
handleMaybeThenable @ (index):936
resolve @ (index):937
resolvePromise @ (index):952
request.onsuccess @ (index):998
IndexedDB (async)
openDB @ (index):1002
get @ (index):998
openStore @ (index):994
get @ (index):994
get @ (index):1004
get @ (index):1003
get @ (index):972
(anonymous) @ (index):1025
phast.scripts.phast.forEachSelectedElement @ (index):1011
(anonymous) @ (index):1025
(anonymous) @ (index):900
phastScripts @ (index):1054
(anonymous) @ (index):1054
__p__.jpg:1 GET https://drift-in.co.uk/themes/drift-in_laundry/assets/img/pages/home/slideshow/responsive/electrolux/electrolux_sxt3vo_c_scale,/plugins/vdlp/phast/phast.php/https-3A-2F-2Fdrift-2Din.co.uk-2Fw_886.jpg/service=images/cacheMarker=/token=2d65a3187818e6a1/__p__.jpg 404
Image (async)
w @ lazysizes.min.js:2
(anonymous) @ lazysizes.min.js:2
(anonymous) @ lazysizes.min.js:2
g @ lazysizes.min.js:2
requestAnimationFrame (async)
h @ lazysizes.min.js:2
(anonymous) @ lazysizes.min.js:2
aa @ lazysizes.min.js:2
U @ lazysizes.min.js:2
h @ lazysizes.min.js:2
setTimeout (async)
(anonymous) @ lazysizes.min.js:2
g @ lazysizes.min.js:2
requestAnimationFrame (async)
h @ lazysizes.min.js:2
(anonymous) @ lazysizes.min.js:2
setTimeout (async)
(anonymous) @ lazysizes.min.js:2
load (async)
(anonymous) @ lazysizes.min.js:2
_ @ lazysizes.min.js:2
F @ lazysizes.min.js:2
(anonymous) @ lazysizes.min.js:2
setTimeout (async)
(anonymous) @ lazysizes.min.js:2
(anonymous) @ lazysizes.min.js:2
(anonymous) @ lazysizes.min.js:2
__p__.jpg:1 GET https://drift-in.co.uk/themes/drift-in_laundry/assets/img/pages/home/slideshow/responsive/dry-cleaning/dry-cleaning_fg9dxm_c_scale,/plugins/vdlp/phast/phast.php/https-3A-2F-2Fdrift-2Din.co.uk-2Fw_824.jpg/service=images/cacheMarker=/token=5d4f3c54390e88ff/__p__.jpg 404
Image (async)
w @ lazysizes.min.js:2
(anonymous) @ lazysizes.min.js:2
(anonymous) @ lazysizes.min.js:2
g @ lazysizes.min.js:2
requestAnimationFrame (async)
h @ lazysizes.min.js:2
(anonymous) @ lazysizes.min.js:2
aa @ lazysizes.min.js:2
U @ lazysizes.min.js:2
h @ lazysizes.min.js:2
setTimeout (async)
(anonymous) @ lazysizes.min.js:2
g @ lazysizes.min.js:2
requestAnimationFrame (async)
h @ lazysizes.min.js:2
(anonymous) @ lazysizes.min.js:2
(anonymous) @ lazysizes.min.js:2
da @ lazysizes.min.js:2
setTimeout (async)
da @ lazysizes.min.js:2
triggerEvent @ (index):1053
(anonymous) @ (index):1052
load (async)
_ @ lazysizes.min.js:2
F @ lazysizes.min.js:2
(anonymous) @ lazysizes.min.js:2
setTimeout (async)
(anonymous) @ lazysizes.min.js:2
(anonymous) @ lazysizes.min.js:2
(anonymous) @ lazysizes.min.js:2
__p__.jpg:1 GET https://drift-in.co.uk/themes/drift-in_laundry/assets/img/pages/home/slideshow/responsive/tumble-dryers/tumble-dryers_rx416m_c_scale,/plugins/vdlp/phast/phast.php/https-3A-2F-2Fdrift-2Din.co.uk-2Fw_786.jpg/service=images/cacheMarker=/token=0f9135f37bb201c3/__p__.jpg 404
Image (async)
w @ lazysizes.min.js:2
(anonymous) @ lazysizes.min.js:2
(anonymous) @ lazysizes.min.js:2
g @ lazysizes.min.js:2
requestAnimationFrame (async)
h @ lazysizes.min.js:2
(anonymous) @ lazysizes.min.js:2
aa @ lazysizes.min.js:2
U @ lazysizes.min.js:2
h @ lazysizes.min.js:2
setTimeout (async)
(anonymous) @ lazysizes.min.js:2
g @ lazysizes.min.js:2
requestAnimationFrame (async)
h @ lazysizes.min.js:2
(anonymous) @ lazysizes.min.js:2
(anonymous) @ lazysizes.min.js:2
da @ lazysizes.min.js:2
setTimeout (async)
da @ lazysizes.min.js:2
triggerEvent @ (index):1053
(anonymous) @ (index):1052
load (async)
_ @ lazysizes.min.js:2
F @ lazysizes.min.js:2
(anonymous) @ lazysizes.min.js:2
setTimeout (async)
(anonymous) @ lazysizes.min.js:2
(anonymous) @ lazysizes.min.js:2
(anonymous) @ lazysizes.min.js:2
__p__.jpg:1 GET https://drift-in.co.uk/themes/drift-in_laundry/assets/img/pages/home/slideshow/responsive/tumble-dryers/tumble-dryers_rx416m_c_scale,/plugins/vdlp/phast/phast.php/https-3A-2F-2Fdrift-2Din.co.uk-2Fw_786.jpg/service=images/cacheMarker=/token=0f9135f37bb201c3/__p__.jpg 404
Image (async)
(anonymous) @ d469825a1cd2f0bf6dbf6d745a72d454-1614253777.js:4
i @ jquery.min.js:2
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
each @ jquery.min.js:2
each @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ d469825a1cd2f0bf6dbf6d745a72d454-1614253777.js:4
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
__p__.jpg:1 GET https://drift-in.co.uk/themes/drift-in_laundry/assets/img/pages/home/slideshow/responsive/electrolux/electrolux_sxt3vo_c_scale,/plugins/vdlp/phast/phast.php/https-3A-2F-2Fdrift-2Din.co.uk-2Fw_886.jpg/service=images/cacheMarker=/token=2d65a3187818e6a1/__p__.jpg 404
Image (async)
(anonymous) @ d469825a1cd2f0bf6dbf6d745a72d454-1614253777.js:4
i @ jquery.min.js:2
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
each @ jquery.min.js:2
each @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ d469825a1cd2f0bf6dbf6d745a72d454-1614253777.js:4
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
__p__.jpg:1 GET https://drift-in.co.uk/themes/drift-in_laundry/assets/img/pages/home/slideshow/responsive/dry-cleaning/dry-cleaning_fg9dxm_c_scale,/plugins/vdlp/phast/phast.php/https-3A-2F-2Fdrift-2Din.co.uk-2Fw_824.jpg/service=images/cacheMarker=/token=5d4f3c54390e88ff/__p__.jpg 404
Image (async)
(anonymous) @ d469825a1cd2f0bf6dbf6d745a72d454-1614253777.js:4
i @ jquery.min.js:2
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
each @ jquery.min.js:2
each @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ d469825a1cd2f0bf6dbf6d745a72d454-1614253777.js:4
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
so I have been updating old framework sources and changing from Jquery logic to javascript  the only problem is that octobercms relies on jquery for some of it resources hence only having it on my local machine  but thank you for responding do quickly

Yours Sincerely

Anthony E Philp

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by apeschar** [comment]
Sorry, I thought you were using the PhastPress plugin for WordPress.

Unfortunately, I don't have the time provide to free support for the October CMS plugin as I didn't create it, and the issue is likely to be in the plugin and not in Phast itself.

**Comment by Artful-dodger** [comment]
Hi Albert,
Thank you once a gain for responding so quickly its a pity that you are only supporting the wordpress plugin is there any pointers you could give me to identify the problem that would be great.

Yours Sincerely

Mr Anthony E Philp

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by apeschar** [comment]
Check the developer console in your browser.

There should be requests to a file called phast.php there.  Those requests are probably failing.  Try opening them and see if you get an error message.

Also, make sure you check your error logs.

**Comment by Artful-dodger** [comment]
Hi Albert,

Thank you  I’ll check that out now and let you know how I get on.

Yours Sincerely

Mr Anthony E Philp

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Artful-dodger** [comment]
HI Albert,

I have just checked the log but nothing is obvious from them  I have included a copy if you wish to take a look I think as the version of stroke7-icon-font.css is more than 5 years old there may be something that is incompatible causing the error. Thank you for your time, just a thought is there any thing I should do to the config/phast.php file.

Yours Sincerely

Mr Anthony E Philp

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Artful-dodger** [comment]
Hi Albert,
Just to keep you update the errors appear to be to do with css validation the Octobercms Frame Work Extra css file only validates against css level 3 + svg I am not sure if there is any settings in the PHAST plugin set for this.

Yours Sincerely
Mr Anthony E Philp

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by apeschar** [comment]
I'm afraid I can't help you with this setup at the moment. :(

At some point I plan to have a look at providing my own October CMS plugin with better compatibility, but for now I don't have anything to add.
