### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by apeschar** [kiboit/phast#19]
We've got our new tokenizer, which is a great step. But there's some work to be done to make it fast.

- [x] Improve timings to include tokenization and serialization
- [x] Add benchmark script
- [x] Use profiler to determine hotspots
- [x] Improve & iterate

## Introduction

Yesterday, I observed processing times of > 7 s for a real-world project. It turns out that most of this was due to Xdebug slowing things down. Without Xdebug, it's not so bad.

~~~
Page automatically optimized by Phast

      CSSInlining\Filter                            75ms
      ScriptsRearrangement\Filter                   10ms
      ImagesOptimizationService\Tags\Filter          5ms
      ScriptsProxyService\Filter                     4ms
      ImagesOptimizationService\CSS\Filter           3ms
      ScriptsDeferring\Filter                        1ms
      DelayedIFrameLoading\Filter                    1ms
      CSSDeferring\Filter                            1ms

                                          (other)  351ms
                                          (total)  456ms
~~~

Nevertheless, the `(other)` bit includes the tokenization and serialization bit and is about 10x worse than the DOMDocument implementation (I'm comparing to Phast on the [live site](https://www.webkarpet.nl)).

## Expand timings
Make the `(other)` bit disappear by also timing the tokenization and serialization phases of processing, and any other significant steps, if any.

## Repeatable benchmark
We should have a (cli) script that runs our full filter pipeline on a real-world input for a few iterations and gives us a reliable number. Just the HTML without images will do. (Download [yesterday's problematic page](https://www.webkarpet.nl/?phast=-phast).)

## Repeatable profiling
Run the above script with PHP 7.0 and XHProf.

PHP 7 because performance factors will differ from PHP 5.6 and we shouldn't optimize for the past. XHProf because Xdebug skews profiling results.

See my latest push to `docker-lamp`: it now has PHP 7, XHProf, and no Xdebug.

## Improvement plan
I suspect the tokenizer is just horrible, but measure first! :)

Here are the random thoughts I have based on yesterday's Xdebug profiling session:

I would suggest replacing the `current()` method by a `$current` property, on one object higher. This would save a whole lot of unnecessary calls to `valid()` and `current()`. Of course the property would get updated on every data consumption that moves the current character.

Also I would suggest replacing the various method calls in `consumeData` by a single `switch` on the `current` character, to make it clear which characters change state, and then by default consume everything that is not that character, as text.

~~~php
// I know this is obvious ;)
switch ($this->input->current) {
// and remove the redundant check in tagOpen and charRef
case '<': return $this->tagOpen();
case '&': return $this->charRef();
default: return $this->consumeAllTextUntil('<&'); 
}
~~~

This should reduce the amount of steps enormously, since we're now processing all the text char by char.

**Comment by mkosturkov** [comment]
The tokenizer performance is improved.
The elements are cached.
The elements list is a doubly linked list.
It's enough for now. Closing.
