### ISSUE TITLE
Serve stylesheets and scripts without PHP

### ISSUE THREAD

**Issue by mkosturkov** [kiboit/phast#28]
* Configure a path in which "generated resources" may be stored.
* The name for a generated resource is determined by the parameters passed to the service, plus the relevant file extension. Keep names human-readable, to aid debugging.
* When outputting a service URL, we check whether the generated resource already exists. If it does, we link there directly.
* When the service is called, we save the response in the generated resource path. (Atomically: create a temporary file in the same directory, then rename.)

**Comment by apeschar** [comment]
* Generate the public store file name based on all the service parameters and only the service parameters. (No need to duplicate last modification time, etc.)
* Only save public store data when the service request is signed.

For expiry:

* Assume a TTL of 24 h.
* If the public store file is older than TTL / 3 (8 h), then `touch()` the file to reset the modification time.
* On cleanup, delete files with a modification time > TTL.
* Generate files with a predictable name, and delete only those files.

**Comment by mkosturkov** [comment]
Sending static files we can not send appropriate caching headers for the resources.
We are putting this on hold until and if we figure something out to fix this matter.
The first ideas are to do some .htaccess hackery and fall back to the php service if they don't work, but this is not very convincing for now.

**Comment by mkosturkov** [comment]
All work has been pushed to the public-resources-storage. If get back to this feature we must finish it with implementing the storage clean-up of old files.
