### ISSUE TITLE
Limit the cache size

### ISSUE THREAD

**Issue by apeschar** [kiboit/phast#34]
In terms of effect:
* Garbage collection should run no more than once per request.
* Limit the cache to a particular size (eg, 500M). When the size is exceeded, clean up until max_size/2 is free (ie, capacity is at 50%).

Implementation-wise:
* Flatten the directory structure: the namespace goes into the hash.
* Implement deeper sharding (configurable from 1-n): ab/cd/ef/ghijklmnopq...
* For garbage collection:
  * Count M shards (lowest-level directories) until we have counted N files.
  * Assume the total cache size is (M/255*shard_depth) * size_sum
  * Keep deleting files until sum_deleted >= total_size - max_size/2

**Comment by mkosturkov** [comment]
The heuristics for calculating the size of the cache is flawed, because the probability of having all possible shard is very low. This gives a lot bigger number than the one we may actually have.
For now we are just going to calculate the actual size of the cache.
