### ISSUE TITLE
Use <link> when a stylesheet can't be retrieved (yet)

### ISSUE THREAD

**Issue by apeschar** [kiboit/phast#59]
The CSSInlining filter now always uses `<style data-phast-params="">` to load stylesheets.

This works asynchronously. That's fine for fonts. But when an actually important stylesheet can't get loaded, we should fall back to loading it synchronously to avoid the flash of unstyled content.

I now quickly fixed this by using a `@import` statement in the `<style>`.

We need to revert to the situation where we had a `<link>` for non-inlined styles.

**Comment by mkosturkov** [comment]
The link should point to the old css service, so the style actually gets cached.

**Comment by mkosturkov** [comment]
Check whether the bundler and the css service use the same cache and make them to if they don't.

**Comment by apeschar** [comment]
See my comment. Please use PRs.
