### ISSUE TITLE
Add font-display: swap to force immediate text rendering

### ISSUE THREAD

**Issue by apeschar** [kiboit/phast#62]
See:
* https://developers.google.com/web/updates/2016/02/font-display
* https://caniuse.com/#feat=css-font-rendering-controls

Essentially, replacing `@font-face{` in CSS with `@font-face{font-display:swap;`.

**Comment by mkosturkov** [comment]
If anybody out there is using this, it is probably with a certain intent which we'll break if we just replace. I propose we only add the swap, if it is not already part of the `@font-face` rule.

**Comment by mkosturkov** [comment]
Actually it will get overridden, if that is the case, so no need to be extra smart.
