### ISSUE TITLE
Insert diagnostic <SCRIPT> inside </BODY> tag

### ISSUE THREAD

**Issue by apeschar** [kiboit/phast#66]
Some trippy WordPress security plugin detects the injected timing script, at the end of the page as a "anomaly".

http://labs.sucuri.net/db/malware/warning?html_anomaly.2

Probably fixed by moving this inside the </HTML> tag.

**Comment by apeschar** [comment]
Alternatively, we can add a placeholder in the injected script, and then replace that placeholder, so we don't have to add anything after serialization...

**Comment by mkosturkov** [comment]
Instead of inserting a script tag, insert a comment like this:.

~~~html
<!--
[Phast] Server-side performance statistics ...
-->
~~~

Then in `phast.js`, find the comment node, and log its contents as was done in the script.

**Comment by apeschar** [comment]
See comments (2).
