### ISSUE TITLE
Optimize CSS without inlining

### ISSUE THREAD

**Issue by apeschar** [kiboit/phast#7]
This issue is a work in progress and needs discussion.

## The issue

Currently, we inline all (local) CSS files before optimizing them. Non-inlined files aren't optimized. This is bad, because many sites have a lot of CSS, and this makes pages _huge_.

What we should do, is inline only the critical parts of the CSS (as currently determined by the CSSOptimization filter). A script would then asynchronously load the actual stylesheets.

## Points of attention

* Integrate CSS optimization in the CSS inliner, then drop CSS optimization filter.
* Some stylesheets still need to be inlined as usual, such as the Google Fonts stylesheets (with IE fix).
* Stylesheets need to be loaded via a service, and be minified.

## Sample output

Replace stylesheet references with this:

~~~html
<style data-phast-href="path/to/style.css" media="all">
/* optimized css */
body { background: blue; }
</style>
~~~

Then at the bottom of the page (with data-phast-no-defer):

~~~
for each element in style[data-phast-href]
  create <link> element with matching href, media
  insert <link> after <style>
  on <link> load
    remove <style>
~~~

**Comment by mkosturkov** [comment]
All the changes are pushed to the css-optimizer branch.
