### ISSUE TITLE
Allow processing incomplete documents

### ISSUE THREAD

**Issue by apeschar** [kiboit/phast#74]
Some systems use AJAX to retrieve HTML snippets after the initial load. Those snippets can contain images, but we cannot process them the normal way because 1) it is not a full HTML document, so Phast refuses it and 2) we should not inject scripts in these snippets because the results mights be unpredictable.

For that reason, we have already added a getForHTMLSnippets() method to the PhastConfiguration in the SDK. However, in order to really make it work, we have to add a configuration option to Phast to force processing all output, not only those that match the regex we have to detect full HTML documents.

We can move the OutputBufferHandler::DOCUMENT_PATTERN to the config-default.php, so it can be overridden in the SDK.

**Comment by mkosturkov** [comment]
Point 1 is done in 1.6.0 release via the 'optimizeHTMLDocumentsOnly' config option.
Point 2 is out of the scope of Phast and is implemented in the plugins SDK.
