### ISSUE TITLE
Minify our scripts

### ISSUE THREAD

**Issue by apeschar** [kiboit/phast#8]
* <s>We should have a build process to minify our scripts.
* We should still have the scripts in PHP, so as to take advantage of opcache.
* Perhaps stick all the scripts in a class, that either reads from files (in development), or is pre-generated (in production).</s>

For now, just use the normal caching mechanism, based on a hash of the script contents.

**Comment by apeschar** [comment]
An idea:

~~~js
(function() {
  var phast = {};
  UTILS(phast);
  SCRIPT 1(phast);
  SCRIPT 2(phast);
});
~~~

**Comment by mkosturkov** [comment]
Pushed to javascripts
